#!/bin/sh /etc/rc.common
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
START=95
export IPFS_PATH=/tmp/ipfs_path

# If IPFS folder doesn't already exist, create one.
if [ ! -d $IPFS_PATH ]
then
	mkdir -p $IPFS_PATH
	cd $IPFS_PATH
	ipfs init
	cp /root/swarm.key $IPFS_PATH
fi

export IPFS_LOGGING=debug

start() {
	echo "Starting IPFS Daemon..."
	cd /root/
	/usr/bin/ipfs config --json Experimental.PreferTLS true
	/usr/bin/ipfs config --json Discovery.MDNS.Interval 1
	# Remove ethernet from swarm options
	/usr/bin/ipfs swarm filters add /ip4/192.168.21.0/ipcidr/24
	# Remove bootstrap peers if any
	ipfs bootstrap rm --all
	# Start IPFS daemon
	/usr/bin/ipfs daemon &> /mnt/mmcblk0p1/ipfs/ipfs.log &
	sleep 1
	/usr/bin/ipfs log level all $IPFS_LOGGING
	ln -s /mnt/mmcblk0p1/ipfs/ipfs.log /var/log/ipfs.log
	cd -
}

stop() {
	echo "Killing IPFS Daemon..."
	ipfs shutdown
}

restart() {
	stop
	start
}
